import argparse
from covid19_outbreak_simulator.cli import summarize_simulations

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        'analyze_logfile',
        description='''Analyze an existing logfile generated by covid19-outbreak-simulator and
            generate summary statistics''')
    parser.add_argument('logfile', help='''Logfile to be analyzed.''')
    args = parser.parse_args()

    summarize_simulations(args.logfile)